# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  lfs: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
    
      #Get current dll files
      #git lfs install
      #git clone https://github.com/Nun-z/RetroArch-Redist.git

      #Get fresh cores from buildbot
      $url = "http://buildbot.libretro.com/nightly/windows/x86_64/RetroArch_cores.7z"
      $output = ".\RetroArchCores.7z"
      Invoke-WebRequest -Uri $url -OutFile $output

      #Get fresh non-core dll files from buildbot
      $url = "http://buildbot.libretro.com/nightly/windows/x86_64/RetroArch_update.7z"
      $output = ".\RetroArchOther.7z"
      Invoke-WebRequest -Uri $url -OutFile $output
      
      #Intsall 7zip extractor
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Set-PSRepository -Name 'PSGallery' -SourceLocation "https://www.powershellgallery.com/api/v2" -InstallationPolicy Trusted
      Install-Module -Name 7Zip4PowerShell -Force
      
      #Extract 7z files
      $sourcefile = ".\RetroArchCores.7z"
      Expand-7Zip -ArchiveFileName $sourcefile -TargetPath '.\tempcores'
      $sourcefile = ".\RetroArchOther.7z"
      Expand-7Zip -ArchiveFileName $sourcefile -TargetPath '.\tempother'

      #Overwrite existing .dll files with new .dll files
      cd tempcores
      cd RetroArch-Win64
      cd cores
      Move-Item -Path ".\*.dll" -Destination D:\a\1\s\RetroArch-Redist\cores -force
      cd ..
      cd ..
      cd ..
      
      #Overwrite existing .dll files with new .dll files
      cd tempother
      cd RetroArch-Win64
      Move-Item -Path ".\*.dll" -Destination D:\a\1\s\RetroArch-Redist\other -force
      cd ..
      cd ..

      #Clean
      Get-ChildItem .\tempcores -Recurse | Remove-Item
      Get-ChildItem .\tempother -Recurse | Remove-Item
      Remove-Item .\RetroArchCores.7z
      Remove-Item .\RetroArchOther.7z
      
      #Send new .dll files to repo
      git lfs install
      git lfs track "*.dll"
      git add .
      git commit -m "Get fresh cores from buildbot"
      git push